name: Build and test, upload to PyPI on release

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        scanpy: ["no", "yes"]
        include:
          - os: macos-latest
            python-version: '3.9'
            scanpy: "yes"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: bash .install_deps.sh
        env:
          USE_SCANPY: ${{ matrix.scanpy }}

      - name: Build
        run: bash .install.sh

      - name: Test
        run: bash .test.sh

